[build]
  functions = "netlify/functions"  # Doit correspondre au dossier réel
  command = "npm install && npm run build"  # Si vous utilisez Node.js

[[redirects]]
  from = "/api/validate"
  to = "/.netlify/functions/validate"
  status = 200